### PR TITLE
Do not use base64

### PR DESCRIPTION
**Pull request by mame**
Ruby 3.4.0 will bundle base64 as a gem. This means `websocket.gemspec` need to explicitly depend on the gem by `gem 'base64'`.

Currently, this gem only uses `Base64.encode64`. So, how about use `Array#pack` instead of the base64 gem?

If you prefer to add `gem 'base64'` to gemspec, let me know. I will be happy to change this PR.

### CODE REVIEW

**Comment by imanel** [comment]
Hi @mame. Could you fix failing Rubocop rule (looks like you need to change double -> single quotes)? I will gladly merge it afterwards.

**Comment by mame** [comment]
@imanel Thank you! I have force-pushed.

**Comment by imanel** [comment]
Merged, thanks for your contribution!

**Comment by imanel** [comment]
And released as part of 1.2.10

**Comment by mame** [comment]
Sorry, I forgot to remove `require 'base64'`. I guess it won't work with ruby 3.4 if it remains. I have created #54.

**Pull request merged**
