### PR TITLE
Use gemspec for specifying dependencies even if they're devel only

### PR DESCRIPTION
**Pull request by skateman**
http://guides.rubygems.org/patterns/#declaring-dependencies

### CODE REVIEW

**Comment by skateman** [comment]
Seems like the `rspec` uses stuff that is not really there in [newer rake versions](https://github.com/ruby/rake/blob/ed197e56cc626725f02431d909e02e048244488e/lib/rake/task_manager.rb#L8), so I had to fix the Rake version to be `< 11.0`. However, I would create a commit that upgrades rspec to 3.5 and to a newer rake if that's okay.

**Comment by imanel** [comment]
I would definitely prefer to have new version of RSpec and relaxed dependency on rake. Could you check if everything is working with `rspec '~> 3.0'`? Since no public API change was expected it should work OOTB. In theory we could bump RSpec version up, but that would probably restrict some of our users.

**Comment by skateman** [comment]
Sure thing!

**Comment by skateman** [comment]
@imanel it seems working, let's wait for Travis

**Comment by imanel** [comment]
Thanks for PR :)

**Comment by skateman** [comment]
You're welcome! More might come as I'm working on a [websocket<->socket proxy](https://github.com/ManageIQ/manageiq/pull/13611) :wink:

**Pull request merged**
