### PR TITLE
Test against Ruby 3.1 on CI

### PR DESCRIPTION
**Pull request by okuramasafumi**

### CODE REVIEW

**Comment by imanel** [comment]
This is super interesting - it was working on 3.0 (fixed bug running it on "3" instead of "3.0" in [here](https://github.com/imanel/websocket-ruby/pull/47)).

My suspect would be changes in [URI](https://github.com/imanel/websocket-ruby/blob/master/lib/websocket/handshake/client.rb#L61), that are returning port 80 as 80 instead of nil, even if it's not provided in original URI (but perhaps only for ws:// protocol?) . Reason why I'm suspecting this is that when [host is provided](https://github.com/imanel/websocket-ruby/blob/master/spec/support/all_client_drafts.rb#L27) the test passes. Technically it's not a bug, but definitely a change in behavior.

I'm currently on vacation without access to computer, so I can only make simple checks and edits via browser, would you have time to check what happened? Alternatively I will be able to do so next week.

**Comment by okuramasafumi** [comment]
@imanel You're right, URI recently introduced `URI::WS` class to represent WebSocket that contains port information.
https://github.com/ruby/uri/commit/805a95786acb20e841dfc450f6b555a8203ec9ab
Previously it returns `URI::Generic` when we call `URI.parse('ws://example.com')`.

**Comment by okuramasafumi** [comment]
Btw, `URI` module currently has a bug not to recognize `wss` protocol. For example, when we run `URI.parse('wss://example.com')` it returns `URI::Generic` object where we should get `URI::WSS`.
I fixed this in https://github.com/ruby/uri/pull/33

**Comment by imanel** [comment]
@okuramasafumi could you try to merge master now to your branch? I hope it's fixed with the latest change, as I'm not making sure that port is always specified (which is as expected), and that default port is never displayed unless required.

**Comment by okuramasafumi** [comment]
@imanel Since there was an error due to old RuboCop not working with Ruby 3.1 because of Yaml incompatibility, I upgrade RuboCop to `0.57.2` but the error still exist.
Maybe we can follow what rspec does?
https://github.com/rspec/rspec-core/blob/main/.github/workflows/ci.yml

**Comment by imanel** [comment]
@okuramasafumi sounds like a good idea - did that, let's see if it's passing now

**Comment by imanel** [comment]
Sounds like it's failing due to updated Rubocop - could you downgrade it? I will merge it then :) Thanks a lot for help on this one!

**Comment by imanel** [comment]
Awesome, thanks for your support!

**Pull request merged**
